// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubtitleCleanUp.Web.Data;

#nullable disable

namespace SubtitleCleanUp.Web.Data.Migrations
{
    [DbContext(typeof(SubtitleCleanupDbContext))]
    partial class SubtitleCleanupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.ChangeProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CanonicalPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FingerprintSignature")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(1400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaStem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedKeeperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupKey", "Status");

                    b.ToTable("ChangeProposals");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.FileOperationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChangeProposalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubtitleFileRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChangeProposalId");

                    b.HasIndex("Status", "Type");

                    b.ToTable("FileOperations");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.ScanIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScanRunId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId");

                    b.ToTable("ScanIssues");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.ScanRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoveredCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProposedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScanRuns");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.SubtitleFileRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChangeProposalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCanonical")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChangeProposalId");

                    b.ToTable("SubtitleFiles");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.FileOperationRecord", b =>
                {
                    b.HasOne("SubtitleCleanUp.Web.Data.ChangeProposal", "Proposal")
                        .WithMany("Operations")
                        .HasForeignKey("ChangeProposalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.ScanIssue", b =>
                {
                    b.HasOne("SubtitleCleanUp.Web.Data.ScanRun", "ScanRun")
                        .WithMany("Issues")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.SubtitleFileRecord", b =>
                {
                    b.HasOne("SubtitleCleanUp.Web.Data.ChangeProposal", "Proposal")
                        .WithMany("Files")
                        .HasForeignKey("ChangeProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.ChangeProposal", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("SubtitleCleanUp.Web.Data.ScanRun", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
